export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOAD_PROFILE = 'LOAD_PROFILE';

export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAILED = 'HOME_VIDEOS_FAILED';

export const SELECTED_VIDEOS_REQUEST = 'SELECTED_VIDEOS_REQUEST';
export const SELECTED_VIDEOS_SUCCESS = 'SELECTED_VIDEOS_SUCCESS';
export const SELECTED_VIDEOS_FAILED = 'SELECTED_VIDEOS_FAILED';

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST';
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS';
export const CHANNEL_DETAILS_FAILED = 'CHANNEL_DETAILS_FAILED';

export const SET_SUBSCRIPTION_STATUS = 'SET_SUBSCRIPTION_STATUS';
