export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const LOAD_PROFILE = 'LOAD_PROFILE';

export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAILED = 'HOME_VIDEOS_FAILED';

export const SELECTED_VIDEOS_REQUEST = 'SELECTED_VIDEOS_REQUEST';
export const SELECTED_VIDEOS_SUCCESS = 'SELECTED_VIDEOS_SUCCESS';
export const SELECTED_VIDEOS_FAILED = 'SELECTED_VIDEOS_FAILED';

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST';
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS';
export const CHANNEL_DETAILS_FAILED = 'CHANNEL_DETAILS_FAILED';

export const COMMENT_LIST_REQUEST = 'COMMENT_LIST_REQUEST';
export const COMMENT_LIST_SUCCESS = 'COMMENT_LIST_SUCCESS';
export const COMMENT_LIST_FAILED = 'COMMENT_LIST_FAILED';

export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS';
export const CREATE_COMMENT_FAILED = 'CREATE_COMMENT_FAILED';

export const RELATED_VIDEO_REQUEST = 'RELATED_VIDEO_REQUEST';
export const RELATED_VIDEO_SUCCESS = 'RELATED_VIDEO_SUCCESS';
export const RELATED_VIDEO_FAILED = 'RELATED_VIDEO_FAILED';

export const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST';
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS';
export const SEARCH_VIDEO_FAILED = 'SEARCH_VIDEO_FAILED';

export const SET_SUBSCRIPTION_STATUS = 'SET_SUBSCRIPTION_STATUS';
